# V0071
# Audit reference: Compact color-coded Halley table only; loads verified V0067 definitions directly and avoids V0069 wrapper namespace failure.
from __future__ import annotations

import math
import subprocess
import sys
import urllib.request
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

VERSION = "V0071"
LOCAL_TZ = ZoneInfo("America/Bogota")
SOURCE_URL = (
    "https://raw.githubusercontent.com/gear66me-ui/"
    "IERS_TN36_V01_MASTER-1/main/"
    "VENUS_1769_V0027_FORMAT_STANDALONE_V0067.py"
)


def require(import_name: str, package_name: str) -> None:
    try:
        __import__(import_name)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "-q", "install", package_name])


for _import_name, _package_name in (
    ("pandas", "pandas"),
    ("IPython", "ipython"),
):
    require(_import_name, _package_name)

import pandas as pd
from IPython.display import HTML, display


def load_base_namespace() -> dict[str, object]:
    request = urllib.request.Request(SOURCE_URL, headers={"User-Agent": VERSION})
    with urllib.request.urlopen(request, timeout=60) as response:
        source = response.read().decode("utf-8")
    if "# V0067" not in source or "def separate_ray_geometry(" not in source:
        raise RuntimeError("Verified V0067 source was not loaded correctly.")
    namespace = {"__name__": "venus_v0067_library", "__file__": "VENUS_1769_V0027_FORMAT_STANDALONE_V0067.py"}
    exec(compile(source, "VENUS_1769_V0027_FORMAT_STANDALONE_V0067.py", "exec"), namespace, namespace)
    required = [
        "build_master",
        "build_cache",
        "separate_ray_geometry",
        "EARTH_RADIUS_KM",
        "IAU1976_AU_KM",
        "ARCSEC_PER_RAD",
    ]
    missing = [name for name in required if name not in namespace]
    if missing:
        raise RuntimeError(f"V0067 source is missing required definitions: {missing}")
    return namespace


def fmt(value: object, decimals: int = 6) -> str:
    if isinstance(value, float):
        return f"{value:,.{decimals}f}"
    return str(value)


def make_table_html(frame: pd.DataFrame) -> str:
    colors = {
        "Earth": "#1d4ed8",
        "Venus": "#7c3aed",
        "Sun": "#b45309",
        "A′B′": "#0f766e",
        "AB": "#92400e",
        "Ratio": "#374151",
        "Parallax": "#4c1d95",
        "Check": "#065f46",
    }
    header = """
    <style>
      .halley-audit-wrap {font-family: DejaVu Sans, Arial, sans-serif; max-width: 1180px;}
      .halley-title {font-size: 20px; font-weight: 800; margin: 8px 0 10px 0; color: #f8fafc; background:#020617; padding:10px 12px; border-radius:8px;}
      table.halley-audit {border-collapse: collapse; width: 100%; background:#020617; color:#e5e7eb; font-size: 13px;}
      table.halley-audit th {background:#1f2937; color:#ffffff; padding:8px; border:1px solid #64748b; text-align:left;}
      table.halley-audit td {padding:7px 8px; border:1px solid #475569;}
      table.halley-audit td.num {text-align:right; font-variant-numeric: tabular-nums;}
      table.halley-audit tr {font-weight:600;}
      .foot {font-size:11px; color:#cbd5e1; background:#020617; padding:8px 12px; border-radius:0 0 8px 8px;}
    </style>
    <div class='halley-audit-wrap'>
    <div class='halley-title'>1769 Venus Transit — Halley Triangle Audit Table — V0071</div>
    <table class='halley-audit'>
      <thead><tr><th>Color</th><th>Quantity</th><th>Symbol</th><th>Value</th><th>Unit</th><th>Trace</th></tr></thead><tbody>
    """
    body = []
    for _, row in frame.iterrows():
        color = colors[str(row["group"])]
        body.append(
            "<tr style='background:" + color + "33;'>"
            f"<td style='background:{color}; width:76px; font-weight:800; color:white;'>{row['group']}</td>"
            f"<td>{row['quantity']}</td>"
            f"<td style='font-weight:800;'>{row['symbol']}</td>"
            f"<td class='num'>{row['value']}</td>"
            f"<td>{row['unit']}</td>"
            f"<td>{row['trace']}</td>"
            "</tr>"
        )
    footer = """
      </tbody></table>
      <div class='foot'>All values are computed from fresh JPL Horizons vectors through the verified V0067 functions. No plot is generated by this audit cell.</div>
    </div>
    """
    return header + "\n".join(body) + footer


def main() -> None:
    ns = load_base_namespace()
    master = ns["build_master"]()
    cache = ns["build_cache"](master)
    geometry = ns["separate_ray_geometry"](cache)

    arcsec_per_rad = float(ns["ARCSEC_PER_RAD"])
    earth_radius_km = float(ns["EARTH_RADIUS_KM"])
    iau1976_au_km = float(ns["IAU1976_AU_KM"])

    a_prime = float(geometry["A_prime_bar_arcsec"])
    b_prime = float(geometry["B_prime_bar_arcsec"])
    rho_arcsec = float(geometry["A_prime_B_prime_arcsec"])
    rho_km = float(geometry["A_prime_B_prime_km"])
    beta_arcsec = float(geometry["AB_arcsec"])
    beta_km = float(geometry["AB_km"])
    ev_km = float(geometry["EV_bar_km"])
    vs_km = float(geometry["VS_bar_km"])
    es_km = float(geometry["ES_bar_km"])
    kappa = ev_km / vs_km
    lam = beta_arcsec / rho_arcsec
    vector_factor = lam / kappa
    pi0_iau76 = math.asin(earth_radius_km / iau1976_au_km) * arcsec_per_rad
    pi0_halley = beta_arcsec * earth_radius_km / beta_km
    pi0_jpl_es = math.asin(earth_radius_km / es_km) * arcsec_per_rad

    rows = [
        ["Earth", "Earth equatorial radius", "R⊕", fmt(earth_radius_km), "km", "IAU 1976 reduction constant"],
        ["Venus", "Earth–Venus reduced distance", "EV̄", fmt(ev_km), "km", "JPL vector projected on ES axis"],
        ["Sun", "Venus–Sun reduced distance", "VS̄", fmt(vs_km), "km", "JPL vector projected on ES axis"],
        ["Sun", "Earth–Sun reduced distance", "ES̄", fmt(es_km), "km", "JPL vector projected on ES axis"],
        ["A′B′", "A′ normal coordinate", "A′", fmt(a_prime), "arcsec", "common-normal tangent-plane coordinate"],
        ["A′B′", "B′ normal coordinate", "B′", fmt(b_prime), "arcsec", "common-normal tangent-plane coordinate"],
        ["A′B′", "Projected Venus-track separation", "ρ = B′ − A′", fmt(rho_arcsec), "arcsec", "same epoch, same normal"],
        ["A′B′", "Projected Venus-track separation", "ρ", fmt(rho_km), "km", "ρ × ES̄ / 206264.806"],
        ["AB", "Projected observer baseline", "β", fmt(beta_arcsec), "arcsec", "AB / (ES̄ / 206264.806)"],
        ["AB", "Projected observer baseline", "AB", fmt(beta_km), "km", "JPL station baseline projected on normal"],
        ["Ratio", "Distance ratio", "κ = EV̄ / VS̄", fmt(kappa, 12), "dimensionless", "Halley triangle distance ratio"],
        ["Ratio", "Angular ratio", "λ = β / ρ", fmt(lam, 12), "dimensionless", "baseline angle divided by track separation"],
        ["Check", "Ratio closure", "λ / κ", fmt(vector_factor, 12), "dimensionless", "1.0 is ideal same-geometry closure"],
        ["Parallax", "Halley solar horizontal parallax", "π₀,H", fmt(pi0_halley, 12), "arcsec", "β × R⊕ / AB"],
        ["Parallax", "JPL Earth–Sun parallax", "π₀,JPL", fmt(pi0_jpl_es, 12), "arcsec", "asin(R⊕ / ES̄)"],
        ["Parallax", "IAU 1976 parallax", "π₀,IAU76", fmt(pi0_iau76, 12), "arcsec", "asin(R⊕ / AU₁₉₇₆)"],
    ]
    frame = pd.DataFrame(rows, columns=["group", "quantity", "symbol", "value", "unit", "trace"])
    display(HTML(make_table_html(frame)))
    print(datetime.now(LOCAL_TZ).strftime("%Y-%m-%d %H:%M:%S %z"))
    print(VERSION)


if __name__ == "__main__":
    main()
# V0071
